name: 'test'
on:
  push:

jobs:
  test:
    name: nvim_rs_test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: rhysd/action-setup-vim@v1
        with:
          version: v0.10.0
          neovim: true
      - run: cargo build
      - run: cargo test
