[application]
# App (Project) Name
name = "so-cold"

# Dioxus App Default Platform
# web, desktop, fullstack
default_platform = "web"

[web.watcher]
# when watcher trigger, regenerate the `index.html`
reload_html = true

# which files or dirs will be watcher monitoring
watch_path = ["src", "assets"]
